### ISSUE TITLE
如何制作推特机器人

### ISSUE THREAD

**Issue by fefe2020** [Pangu2020together/requirements-or-questions#2]
**#推特机器人**
###  发推功能
> 能够自动剪切一段视频或者文字或者表情包，由机器人自动发推文
### 回复功能
> 推特公众号自动回复私信和留言
### 点赞功能
> 自动点赞转发本推的帖子
### 其他待补充

谢谢@Pangu2020together

**Comment by Pangu2020together** [comment]
这个教程写得很直白
https://learn.g2crowd.com/how-to-make-a-twitter-bot

**Comment by Pangu2020together** [comment]
但更多自定义功能需要涉及到 coding 以及 self-hosting。

**Comment by Pangu2020together** [comment]
Github 上有很多成熟的案例项目，搜索 `twitter bot` 一大堆。

**Comment by fefe2020** [comment]
Get it,谢谢🐱哥

2020 相聚盘古 <notifications@github.com> 於 2019年5月9日 週四 上午8:02寫道：
