### ISSUE TITLE
仅要求搜索功能的静态网页

### ISSUE THREAD

**Issue by ruojiezhaoran** [Pangu2020together/requirements-or-questions#3]
妄议热线的 timestamp 整理，每天仅几百字。但是常年累月下来，总量不小。需要存放在一个地方，仅仅是便于搜索查找。请问存放在哪里最合适？
具体的特点和要求有以下几点：

1. 格式要求非常低，不需要加图片，但最好可以加超链（曾经用非常轻量的etherpad，虽然不被墙，但墙内反映缓冲慢）。
2. 由于总量很大，最好有局部的折叠功能，类似于 code 的那种。
3. 全文搜索功能。不想用 blog 模式的原因就在于此，由于每篇文章都很短，不太适合做一篇，倒是可以以月份为单位整理，但很多地方也没办法跨博文检索。

请指教，非常感谢！

**Comment by Pangu2020together** [comment]
Github issues 可完美解决你上述所有需求。
你的门槛只有 Markdown 语法（10 分钟上手）。

每期节目对应一个 issue，可长可短。

***

超链接随便加，语法是 `[链接文字](链接 URL)`。

***

Markdown 默认不支持折叠功能，但你可以直接写原生 HTML，请参考这个 Gist：
<details>
  <summary>点我展开 Gist 链接</summary>
  https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab  
</details>

***

全文搜索是标配，Github issues 还支持更加强大的搜索，可参考官方文章：
https://help.github.com/en/articles/searching-issues-and-pull-requests

***

如果是你私人备份使用，你还可以开一个 Github private repo。

**Comment by Pangu2020together** [comment]
最后提醒一句，Github 会针对大陆的 IP 屏蔽掉某些敏感的 repo（代码仓库）。
因此，请不要指望着可以让不懂翻墙的战友也能无障碍看到所有内容。
这样子你还不如用加设密码的 zip 压缩包传播资料。

**Comment by Pangu2020together** [comment]
最后的最后，必须提醒的是，所有的资料都得自己有备份（例如 Dropbox、iCloud 等）。

**Comment by Pangu2020together** [comment]
如果没有什么问题的话，你可以 close issue。

**Comment by ruojiezhaoran** [comment]
非常感谢！
我肯定不指望不翻墙的人可以看到内容。妄议热线的一个搜索帖而已，不看节目的人根本不可能看这个。主要就是三个听写员每天需要靠听力辨认一些听众，靠搜索可以迅速定位之前的节目内容，回听做对比。
再次感谢！
