### ISSUE TITLE
做“伪”中文热搜榜

### ISSUE THREAD

**Issue by fefe2020** [Pangu2020together/requirements-or-questions#4]
做“伪”中文热搜榜

人们对于别人正在关注什么始终抱有好奇心
然后中文世界始终没有统一的热搜榜

以下是我的构想：
人工创建一个中文热词库
借助 google trends，运用一个开源伪API
每天将词库中的词遍历搜索
再对比产生热搜榜

本人编程经验能力非常有限，且近期极忙
求小天使降临
for a friend````

**Comment by Pangu2020together** [comment]
这个是伪需求，而且分分钟会被老共轰瘫（很容易超出 API 限制）
